// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Smart_Event_Management_and_Ticketing_System.Data;

#nullable disable

namespace Smart_Event_Management_and_Ticketing_System.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260202070407_AddMemberRole")]
    partial class AddMemberRole
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Smart_Event_Management_and_Ticketing_System.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SeatType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("BookingId");

                    b.HasIndex("EventId");

                    b.HasIndex("MemberId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Smart_Event_Management_and_Ticketing_System.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("EventId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            EventId = 1,
                            Category = "Music",
                            Description = "An enchanting evening of classical music featuring renowned orchestra performers.",
                            EventDate = new DateTime(2025, 6, 15, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            EventName = "Metropolitan Orchestra: Symphony Night",
                            Price = 45.00m,
                            TotalSeats = 500,
                            Venue = "Grand Concert Hall"
                        },
                        new
                        {
                            EventId = 2,
                            Category = "Art",
                            Description = "Explore modern art from local and international artists.",
                            EventDate = new DateTime(2025, 5, 20, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            EventName = "Contemporary Art Exhibition",
                            Price = 15.00m,
                            TotalSeats = 200,
                            Venue = "City Art Gallery"
                        },
                        new
                        {
                            EventId = 3,
                            Category = "Theater",
                            Description = "A dramatic performance of the classic tragedy by William Shakespeare.",
                            EventDate = new DateTime(2025, 7, 10, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            EventName = "Shakespeare's Hamlet",
                            Price = 35.00m,
                            TotalSeats = 350,
                            Venue = "Metropolitan Theater"
                        },
                        new
                        {
                            EventId = 4,
                            Category = "Music",
                            Description = "Smooth jazz performances by award-winning musicians.",
                            EventDate = new DateTime(2025, 5, 30, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            EventName = "Jazz Night Live",
                            Price = 25.00m,
                            TotalSeats = 150,
                            Venue = "Blue Note Jazz Club"
                        },
                        new
                        {
                            EventId = 5,
                            Category = "Dance",
                            Description = "A celebration of diverse cultural dance traditions from around the world.",
                            EventDate = new DateTime(2025, 8, 5, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            EventName = "Cultural Dance Festival",
                            Price = 30.00m,
                            TotalSeats = 400,
                            Venue = "City Cultural Center"
                        },
                        new
                        {
                            EventId = 6,
                            Category = "Workshop",
                            Description = "Learn advanced photography techniques from professional photographers.",
                            EventDate = new DateTime(2025, 6, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            EventName = "Photography Workshop",
                            Price = 50.00m,
                            TotalSeats = 30,
                            Venue = "Community Arts Space"
                        });
                });

            modelBuilder.Entity("Smart_Event_Management_and_Ticketing_System.Models.Inquiry", b =>
                {
                    b.Property<int>("InquiryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InquiryId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("InquiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("InquiryId");

                    b.ToTable("Inquiries");
                });

            modelBuilder.Entity("Smart_Event_Management_and_Ticketing_System.Models.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PreferredCategory")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MemberId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Members");
                });

            modelBuilder.Entity("Smart_Event_Management_and_Ticketing_System.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ReviewId");

                    b.HasIndex("EventId");

                    b.HasIndex("MemberId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Smart_Event_Management_and_Ticketing_System.Models.Booking", b =>
                {
                    b.HasOne("Smart_Event_Management_and_Ticketing_System.Models.Event", "Event")
                        .WithMany("Bookings")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Smart_Event_Management_and_Ticketing_System.Models.Member", "Member")
                        .WithMany("Bookings")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Smart_Event_Management_and_Ticketing_System.Models.Review", b =>
                {
                    b.HasOne("Smart_Event_Management_and_Ticketing_System.Models.Event", "Event")
                        .WithMany("Reviews")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Smart_Event_Management_and_Ticketing_System.Models.Member", "Member")
                        .WithMany("Reviews")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Smart_Event_Management_and_Ticketing_System.Models.Event", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Smart_Event_Management_and_Ticketing_System.Models.Member", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
